#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FULL_PATH = ROOT / "core" / "core-full.md"
MIN_PATH = ROOT / "core" / "core-min.md"
STD_PATH = ROOT / "core" / "core.md"

MIN_START = "<!-- tier:min:start -->"
MIN_END = "<!-- tier:min:end -->"
STD_START = "<!-- tier:standard:start -->"
STD_END = "<!-- tier:standard:end -->"
GENERATED_NOTE = "<!-- Generated by scripts/sync-core.py. Do not edit directly. -->"


def extract_blocks(lines: list[str]) -> tuple[list[str], list[str]]:
    min_block: list[str] = []
    std_block: list[str] = []
    in_min = False
    in_std = False
    for line in lines:
        if line.strip() == MIN_START:
            in_min = True
            continue
        if line.strip() == MIN_END:
            in_min = False
            continue
        if line.strip() == STD_START:
            in_std = True
            continue
        if line.strip() == STD_END:
            in_std = False
            continue
        if in_min:
            min_block.append(line)
        if in_std:
            std_block.append(line)
    return min_block, std_block


def build_min(lines: list[str]) -> str:
    min_block, _ = extract_blocks(lines)
    content = [
        "# Core Context (Min)\n",
        "\n",
        f"{GENERATED_NOTE}\n",
        "\n",
        *min_block,
    ]
    return "".join(content).rstrip() + "\n"


def build_standard(lines: list[str]) -> str:
    min_block, std_block = extract_blocks(lines)
    content = [
        "# Core Context (Standard)\n",
        "\n",
        f"{GENERATED_NOTE}\n",
        "\n",
        *min_block,
        "\n",
        *std_block,
    ]
    return "".join(content).rstrip() + "\n"


def read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines(keepends=True)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify files are in sync")
    args = parser.parse_args()

    full_lines = read_lines(FULL_PATH)
    min_content = build_min(full_lines)
    std_content = build_standard(full_lines)

    if args.check:
        ok = True
        if not MIN_PATH.exists() or MIN_PATH.read_text(encoding="utf-8") != min_content:
            print("core-min.md is out of sync. Run scripts/sync-core.py.")
            ok = False
        if not STD_PATH.exists() or STD_PATH.read_text(encoding="utf-8") != std_content:
            print("core.md is out of sync. Run scripts/sync-core.py.")
            ok = False
        return 0 if ok else 1

    write_if_changed(MIN_PATH, min_content)
    write_if_changed(STD_PATH, std_content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
