#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_FILES = [
    "README.md",
    "core/core-full.md",
    "core/core.md",
    "core/core-min.md",
    "frontend.md",
    "backend.md",
    "collaboration-protocol.md",
    "docs/usage.md",
    "docs/user-guide.md",
    "docs/usage-zh.md",
    "docs/verification.md",
    "docs/versioning.md",
    "docs/release.md",
    "docs/release-zh.md",
    "docs/faq.md",
    "docs/contracts/README.md",
    "adapters/cursor.md",
    "adapters/claude.md",
    "adapters/plain.md",
    "scripts/release.sh",
    "scripts/verify.sh",
    "scripts/release.ps1",
    "scripts/verify.ps1",
    "scripts/release.cmd",
    "scripts/verify.cmd",
    "templates/contracts/CHANGELOG.md",
    "templates/contracts/openapi/openapi.yaml",
    "templates/contracts/proto/service/v1/service.proto",
]

GENERATED_NOTE = "<!-- Generated by scripts/sync-core.py. Do not edit directly. -->"
TIER_MARKERS = [
    "<!-- tier:min:start -->",
    "<!-- tier:min:end -->",
    "<!-- tier:standard:start -->",
    "<!-- tier:standard:end -->",
]


def fail(message: str) -> int:
    print(message)
    return 1


def main() -> int:
    for relative in REQUIRED_FILES:
        path = ROOT / relative
        if not path.exists():
            return fail(f"Missing required file: {relative}")
        if path.stat().st_size == 0:
            return fail(f"Empty file: {relative}")

    core_min = (ROOT / "core" / "core-min.md").read_text(encoding="utf-8")
    core_std = (ROOT / "core" / "core.md").read_text(encoding="utf-8")
    for content, name in [(core_min, "core-min.md"), (core_std, "core.md")]:
        if GENERATED_NOTE not in content:
            return fail(f"Missing generated note in {name}")
        for marker in TIER_MARKERS:
            if marker in content:
                return fail(f"Tier marker found in {name}: {marker}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
